<template>
    <DefaultLayout>
        <section class="p-4">
            <header>
                <h1 class="text-3xl font-extrabold pb-4">About MaveDB</h1>
            </header>
            <main class="leading-relaxed flex flex-col space-y-4">
                <p>
                MaveDB is a public repository for datasets from Multiplexed Assays of Variant Effect (MAVEs),
                such as those generated by deep mutational scanning (DMS) or massively parallel reporter assay
                (MPRA) experiments. MaveDB is composed of community contributed datasets uploaded by
                researchers worldwide. If you wish to contribute your own data, please see the
                <router-link to="/docs">documentation</router-link> page for more information.
                </p>
                <p>
                Although MAVEs are often performed on synthetic targets, we also support data uploaded with
                respect to reference sequences from Ensembl and RefSeq. We resolve these sequence accessions
                using <a href="https://cdot.cc">CDOT</a> and Seqrepo (see
                <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7714221/"> Hart et al. 2020</a>). Variants
                are parsed and validated against provided sequences using the
                <a href="https://hgvs.readthedocs.io/en/stable/">hgvs</a> Python library developed by
                Biocommons.
                </p>
                <p>
                To better support interpretation of functional MAVE data, we map and link variants to known
                human variation after performing internal validation. First, the target sequence is mapped
                to a human reference sequence. For more information on this mapping process, please refer to
                <a href="https://genomebiology.biomedcentral.com/articles/10.1186/s13059-025-03647-x">Arbesfeld et al. 2025</a>.
                Once each variant is mapped to a reference sequence, we submit variants to the ClinGen Allele
                Registry and obtain a unique ClinGen Allele Identifier (CAID) for each variant. This CAID and
                the existing work from ClinGen allows us to link MaveDB variants to existing clinical and
                population databases, such as ClinVar and gnomAD. For more information, please see the
                <a href="https://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/landing">ClinGen Allele Registry</a>.
                This ClinGen integration also underpins our search feature, enabling users to search for
                variants of interest across MaveDB datasets.
                </p>
                <p>
                MaveMD (MAVEs for MeDicine) is an interface that integrates ClinVar and ClinGen Allele
                Registry data as described above, displays clinical evidence calibrations, provides intuitive
                visualizations, and exports structured evidence compatible with ACMG/AMP variant
                classification guidelines. MaveMD currently contains 438,318 variant effect measurements
                mapped to the human genome from 74 MAVE datasets spanning 32 disease-associated genes. For a
                complete list of curated datasets, please see the
                <router-link to="/collections/urn:mavedb:collection-603dafbf-4a3f-4d70-ab8c-aafb226fbff4">MaveMD dataset collection</router-link>.
                To search directly for variants, navigate to the <router-link to="/mavemd">MaveMD</router-link>
                search feature and enter a valid HGVS string.
                </p>
                <p>
                In addition to the user interface, MaveDB provides a REST API for programmatic access to all
                public data. The API is documented using the OpenAPI specification. You can find the
                documentation at the following link: <a href="https://api.mavedb.org/docs">API documentation</a>.
                </p>
                <p>
                In collaboration with <a href="https://www.ga4gh.org/">GA4GH</a>, we allow users to export
                uploaded variant data in
                <a href="https://www.ga4gh.org/product/variation-representation/">Variant Representation Specification (VRS)</a>
                format and allow the export of experiment and score set data using the
                <a href="https://www.ga4gh.org/product/variant-annotation/">Variant Annotation (VA)</a>
                standard. Both specifications allow greater interoperability between computational tools and databases.
                </p>
                <p>
                MaveDB is open-source and released under the
                <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">AGPLv3</a>
                license. MaveDB is hosted by the
                <a href="https://faculty.washington.edu/dfowler/index.html">Fowler Lab</a>
                in the
                <a href="https://www.gs.washington.edu/">Department of Genome Sciences</a>
                at the University of Washington. It is supported and developed by the
                <a href="https://www.washington.edu/">University of Washington</a>,
                the
                <a href="https://www.wehi.edu.au/">Walter and Eliza Hall Institute of Medical Research</a>,
                and the
                <a href="https://brotmanbaty.org/">Brotman Baty Institute.</a>
                </p>
                <p>
                For details about the MaveDB software, including release notes, upcoming features, and source code, please see the GitHub
                repositories for our <a href="https://github.com/VariantEffect/mavedb-api">API</a> and
                <a href="https://github.com/VariantEffect/mavedb-ui">UI</a>. If you have questions, comments, or suggestions, check out
                the <router-link to="/help">Help & Support</router-link> page for information about how to get in touch.
                </p>
                <hr style="border:0; border-top:1px solid #ccc; height:0; margin:1.5rem 0;" />

                <h2 class="text-2xl font-extrabold">Citing MaveDB</h2>
                <p>
                To cite MaveDB, please cite our most recent publication:
                </p>
                <blockquote class="ml-10">
                    Rubin, A.F., Stone, J., Bianchi, A.H. <i>et al.</i> MaveDB 2024: a curated community database with over seven million variant effects
                    from multiplexed functional assays. <i>Genome Biol</i> <b>26</b>, 13 (2025). <a href=https://doi.org/10.1186/s13059-025-03476-y>https://doi.org/10.1186/s13059-025-03476-y</a>
                </blockquote>
                <p>Previous MaveDB publications are listed below:</p>
                <blockquote class="ml-10">
                Daniel Esposito, Jochen Weile, Jay Shendure, Lea M Starita, Anthony T Papenfuss, Frederick P Roth, Douglas M Fowler, Alan F Rubin.
                MaveDB: an open-source platform to distribute and interpret data from multiplexed assays of variant effect.
                <i>Genome Biol</i> <b>20</b>, 223 (2019). <a href="https://doi.org/10.1186/s13059-019-1845-6">https://doi.org/10.1186/s13059-019-1845-6</a>
                </blockquote>
            </main>
        </section>
    </DefaultLayout>
</template>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import DefaultLayout from '@/components/layout/DefaultLayout.vue';

export default defineComponent({
    name: 'AboutView',
    components: { DefaultLayout },

    setup() {
        onMounted(() => {
            // init logic
        });
        return {};
    }
});
</script>
