<template>
  <DefaultLayout>
    <div class="grid" style="margin: 10px 0;">
      <div class="col-12">
        <p class="mavedb-mavemd-notice">
          <router-link to="/mavemd"><img alt="MaveMD" class="mavedb-mavemd-logo" src="@/assets/mavemd-logo.png" /></router-link>
          &nbsp;
          Looking for the new MaveMD clinical features? <router-link to="/mavemd">Click here.</router-link>
        </p>
      </div>
      <div class="col-8">
        <Card>
          <template #title>About</template>
          <template #content>
            <p>
              MaveDB is a public repository for datasets from Multiplexed Assays of Variant Effect (MAVEs), such as those
              generated by deep mutational scanning (DMS) or massively parallel reporter assay (MPRA) experiments.
            </p>
            <p>
              MaveDB is open-source, released under the
              <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">AGPLv3</a>
              license.
            </p>
            <p>
              MaveDB is hosted by the
              <a href="https://faculty.washington.edu/dfowler/index.html">Fowler Lab</a>
              in the
              <a href="https://www.gs.washington.edu/">Department of Genome Sciences</a>
              at the University of Washington. It is supported and developed by the
              <a href="https://www.washington.edu/">University of Washington</a>,
              the
              <a href="https://www.wehi.edu.au/">Walter and Eliza Hall Institute of Medical Research</a>,
              and the
              <a href="https://brotmanbaty.org/">Brotman Baty Institute.</a>
            </p>
            <p>
              If you have questions, comments, or suggestions, check out the <router-link to="/help">Help & Support</router-link> page
              for information about how to get in touch.
            </p>
          </template>
        </Card>
      </div>
      <div class="col-4">
        <Card>
          <template #title>Featured Searches</template>
          <template #content>
            <table>
              <thead>
                <tr>
                  <th>Organisms</th>
                  <th>Target genes</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <ul>
                      <li><router-link :to="{name: 'search', query: {search: 'Homo sapiens'}}">Homo sapiens</router-link></li>
                      <li><router-link :to="{name: 'search', query: {search: 'Mus musculus'}}">Mus musculus</router-link></li>
                      <li><router-link :to="{name: 'search', query: {search: 'Saccharomyces cerevisiae S288C'}}">Saccharomyces cerevisiae S288C</router-link></li>
                    </ul>
                  </td>
                  <td>
                    <ul>
                      <li><router-link :to="{name: 'search', query: {search: 'HSP90'}}">HSP90</router-link></li>
                      <li><router-link :to="{name: 'search', query: {search: 'KCNQ4'}}">KCNQ4</router-link></li>
                      <li><router-link :to="{name: 'search', query: {search: 'TEM-1 β-lactamase'}}">TEM-1 β-lactamase</router-link></li>
                    </ul>
                  </td>
                </tr>
              </tbody>
            </table>
          </template>
        </Card>
      </div>
      <div class="col-12">
        <HighlightsView model="ScoreSet"></HighlightsView>
      </div>
      <div class="col-8">
        <HighlightsView model="Target"></HighlightsView>
      </div>
      <div class="col-4">
        <Card>
          <template #title>News</template>
          <template #content>
            <ul>
              <li>
                <p>Tracks for many score sets are now available on the UCSC Genome Browser.</p>
                <p>
                  Example:
                  <a href="https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr17:43051063-43051117&hubUrl=https://public.gi.ucsc.edu/~cline/mavedb/hub/hub.txt&Variant_Effect_Maps_hideKids=1&BRCA1_00000097-s-1=dense" target="_blank">
                    <img alt="UCSC Genome Browser" src="@/assets/logo-ucsc-genome-browser.png" style="height: 20px;" />
                    UCSC Genome Browser
                  </a>
                  track for
                  <router-link :to="{name: 'scoreSet', params: {urn: 'urn:mavedb:00000097-s-1'}}">BRCA1 SGE Exon 20 Replicate 1</router-link>
                </p>
              </li>
              <li>
                The complete set of MAVE data licensed under
                <a href="https://creativecommons.org/public-domain/cc0/" target="_blank">Creative Commons Zero</a>
                can now be downloaded from <a href="https://doi.org/10.5281/zenodo.11201736" target="_blank">Zenodo</a>.
              </li>
            </ul>
          </template>
        </Card>
      </div>
      <div class="col-12">
        <Card>
          <template #title>Citing MaveDB</template>
          <template #content>
            <p>
              To cite MaveDB, please cite our most recent publication:
            </p>
            <blockquote>
                Rubin, A.F., Stone, J., Bianchi, A.H. <i>et al.</i> MaveDB 2024: a curated community database with over seven million variant effects
                from multiplexed functional assays. <i>Genome Biol</i> <b>26</b>, 13 (2025). <a href=https://doi.org/10.1186/s13059-025-03476-y>https://doi.org/10.1186/s13059-025-03476-y</a>
            </blockquote>
            Previous MaveDB publications are listed below:
            <blockquote>
              Daniel Esposito, Jochen Weile, Jay Shendure, Lea M Starita, Anthony T Papenfuss, Frederick P Roth, Douglas M Fowler, Alan F Rubin.
              MaveDB: an open-source platform to distribute and interpret data from multiplexed assays of variant effect.
              <i>Genome Biol</i> <b>20</b>, 223 (2019). <a href="https://doi.org/10.1186/s13059-019-1845-6">https://doi.org/10.1186/s13059-019-1845-6</a>
            </blockquote>
          </template>
        </Card>
      </div>
    </div>
  </DefaultLayout>
</template>

<script>
import Card from 'primevue/card'

import config from '@/config'
import DefaultLayout from '@/components/layout/DefaultLayout'
import HighlightsView from '@/components/common/HighlightsView.vue';

export default {
  name: 'HomeScreen',
  components: {Card, DefaultLayout, HighlightsView},
  data: function() {
    return {config}
  },

  methods: {
    copyText: function(event) {
      const element = event.target
      if (element) {
        navigator.clipboard.writeText(element.innerText)
      }
    }
  }
}
</script>

<style scoped>
td, th {
  padding: 0 5px;
  vertical-align: top;
}

ul {
  padding-left: 1em;
}

.mave-hgvs-example {
  background: #eee;
  padding: 0 3px;
  cursor: pointer;
}

.mavedb-mavemd-notice {
  text-align: center; font-size: 120%;
}

.mavedb-mavemd-logo {
  height: 40px;
  vertical-align: middle;
}
</style>
