<template>
  <DefaultLayout>
    <div class="grid" style="margin: 10px 0;">
      <div class="col-8">
        <Card>
          <template #title>About</template>
          <template #content>
            <p>
              MaveDB is a public repository for datasets from Multiplexed Assays of Variant Effect (MAVEs), such as those
              generated by deep mutational scanning (DMS) or massively parallel reporter assay (MPRA) experiments.
            </p>
            <p>
              MaveDB is open-source, released under the
              <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">AGPLv3</a>
              license.
            </p>
            <p>
              MaveDB is hosted by the
              <a href="https://faculty.washington.edu/dfowler/index.html">Fowler Lab</a>
              in the
              <a href="https://www.gs.washington.edu/">Department of Genome Sciences</a>
              at the University of Washington. It is supported and developed by the
              <a href="https://www.washington.edu/">University of Washington</a>,
              the
              <a href="https://www.wehi.edu.au/">Walter and Eliza Hall Institute of Medical Research</a>,
              and the
              <a href="https://brotmanbaty.org/">Brotman Baty Institute.</a>
            </p>
          </template>
        </Card>
      </div>
      <div class="col-4">
        <Card>
          <template #title>Featured Searches</template>
          <template #content>
            <table>
              <thead>
                <tr>
                  <th>Organisms</th>
                  <th>Target genes</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <ul>
                      <li><router-link :to="{name: 'search', query: {search: 'Homo sapiens'}}">Homo sapiens</router-link></li>
                      <li><router-link :to="{name: 'search', query: {search: 'Mus musculus'}}">Mus musculus</router-link></li>
                      <li><router-link :to="{name: 'search', query: {search: 'Saccharomyces cerevisiae S288C'}}">Saccharomyces cerevisiae S288C</router-link></li>
                    </ul>
                  </td>
                  <td>
                    <ul>
                      <li><router-link :to="{name: 'search', query: {search: 'HSP90'}}">HSP90</router-link></li>
                      <li><router-link :to="{name: 'search', query: {search: 'KCNQ4'}}">KCNQ4</router-link></li>
                      <li><router-link :to="{name: 'search', query: {search: 'TEM-1 β-lactamase'}}">TEM-1 β-lactamase</router-link></li>
                    </ul>
                  </td>
                </tr>
              </tbody>
            </table>
          </template>
        </Card>
      </div>
      <div class="col-12">
        <HighlightsView model="ScoreSet"></HighlightsView>
      </div>
      <div class="col-8">
        <HighlightsView model="Target"></HighlightsView>
      </div>
      <div class="col-4">
        <Card>
          <template #title>Citation</template>
          <template #content>
            <p>
              MaveDB: an open-source platform to distribute and interpret data from multiplexed assays of variant Effect
            </p>
            <p>
              Daniel Esposito, Jochen Weile, Jay Shendure, Lea M Starita, Anthony T Papenfuss, Frederick P Roth, Douglas M Fowler, Alan F Rubin
            </p>
            <p>
              Genome Biol 20, 223 (2019) <a href="https://doi.org/10.1186/s13059-019-1845-6">doi:10.1186/s13059-019-1845-6</a>
            </p>
          </template>
        </Card>
      </div>
    </div>
  </DefaultLayout>
</template>

<script>

import Card from 'primevue/card'
//import InputText from 'primevue/inputtext'

//import config from '@/config'
import DefaultLayout from '@/components/layout/DefaultLayout'
import HighlightsView from '@/components/common/HighlightsView.vue';

export default {
  name: 'HomeScreen',
  components: {Card, DefaultLayout, HighlightsView}
}

</script>

<style scoped>

td, th {
  padding: 0 5px;
  vertical-align: top;
}

ul {
  padding-left: 1em;
}

</style>
