name: Build (On Push)
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: npm ci
    - run: npx browserslist@latest --update-db
    - run: npm run build
#    - run: npm test
